codecov:
  branch: dev

coverage:
  precision: 2
  round: down
  range: "35...85"

ignore:
  - "shared"
  - "hybrid"
  - "native"
  - "libs/**/*Test*/*"

comment:
  layout: "reach, diff"
  behavior: default
  require_changes: true 
