version: 2
jobs:
  build-and-test:
    working_directory: ~/SalesforceMobileSDK-iOS
    macos:
      xcode: "9.2.0"
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
#      - restore_cache:
#          keys:
#            - v1-gems-{{ checksum ".circleci/Gemfile.lock" }}
#            - v1-gems-
      - run:
          name: Install Dependencies
          command:  |
            npm install shelljs@0.7.0
            ./install.sh
            ./build/pre-build
            chruby 2.4.2
            echo "Gem Home: ${GEM_HOME}"
            echo "Gem Path: ${GEM_PATH}"
            gem install --no-document fastlane -v 2.75
            gem install slather
            gem install xcov
            gem install danger
            gem install danger-xcov
            gem install danger-junit
            gem install plist
            gem install CFPropertyList -v 2.3.6
#            gem install bundler
#            bundle check || bundle install --path $GEM_PATH
#      - save_cache:
#          key: v1-gems-{{ checksum ".circleci/Gemfile.lock" }}
#          paths:
#            - ~/.gem/$ruby/$version
      - run:
          name: Run tests
          command: bundle exec fastlane PR
      - store_test_results:
          path: test_output/
          destination: Test-Results
      - store_test_results:
          path: clangReport/
          destination: Static-Analysis
      - store_test_results:
          path: slather_output/
          destination: Code-Coverage
      - run:
          name: Codecov Uplaod
          command: bash <(curl -s https://codecov.io/bash) -f slather_output/cobertura.xml -X coveragepy -X gcov -X xcode

workflows:
  version: 2

  build-test-pr:
    jobs:
      - build-and-test

